name: Dump Supabase Schema

on:
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Dump schema (public, auth, storage)
  run: |
    mkdir -p supabase_summary
    DB_URL='${{ secrets.SUPABASE_DB_URL }}'
    # Windows CR ve son satır sonunu kes:
    DB_URL="${DB_URL%%[$'\r\n']*}"
    pg_dump "$DB_URL" \
      -s -n public -n auth -n storage \
      --no-owner --no-privileges \
      -f supabase_summary/schema.sql
    head -n 40 supabase_summary/schema.sql || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-schema
          path: supabase_summary/schema.sql
          if-no-files-found: error
